### ISSUE TITLE
Build error: extension `zicsr' required

### ISSUE THREAD

**Issue by ohmytime** [mo10/ch58x-cmake-template#1]
I used your template and ran into compilation issues,
```
Error: unrecognized opcode `csrr a5,mstatus', extension `zicsr' required
```

Then I found a solution for your reference.

https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/aE1ZeHHCYf4

**Comment by mo10** [comment]
Which compiler are you using?

**Comment by ohmytime** [comment]
riscv-none-elf-gcc (xPack GNU RISC-V Embedded GCC arm64) 12.3.0

https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack

**Comment by ohmytime** [comment]
And I get a clue in here:
https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/aE1ZeHHCYf4

I solve this issue by adding this option
```
-misa-spec=2.2 
```

Maybe this is a temporary solution, can you use the method he recommended, I don't know how to put 
```
--with-isa-spec=2.2
```
into CMakeLists

**Comment by ohmytime** [comment]
Now I know
```
-march=rv32imac_zicsr
```

**Comment by mo10** [comment]
> And I get a clue in here: https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/aE1ZeHHCYf4
> 
> I solve this issue by adding this option
> 
> ```
> -misa-spec=2.2 
> ```
> 
> Maybe this is a temporary solution, can you use the method he recommended, I don't know how to put
> 
> ```
> --with-isa-spec=2.2
> ```
> 
> into CMakeLists

> Now I know
> 
> ```
> -march=rv32imac_zicsr
> ```

This project is based on MSR(MounRiver Studio) compiler. I have not tested it on the xPack compiler.

AFAIK the MSR compiler seems to have some special modifications.

I am currently busy with other things. I will take a look at this on the weekend. 

Thank you!
